version: '3.5'
services:
  znuny-server:
    container_name: znuny
    image: znuny:6.0.37.1
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    volumes:
      - ${PWD}/Config.pm:/opt/otrs/Kernel/Config.pm:rw
        #      - ${PWD}/ZZZAAuto.pm:/opt/otrs/Kernel/Config/Files/ZZZAAuto.pm:rw
networks:
  frontend:
    name: network-hml
    external: true